version: "3"

services:

  whoami:
    image: tutum/hello-world #imagen del contenedor
    networks:
      - webnet #Para la red
    ports:
      - "192.168.1.13:80:80" 
    logging:
      driver: "fluentd" # Logging Driver 
      options:
        fluentd-address: 192.168.1.22:24224  #Especifique una dirección de socket para conectarse al daemon Fluentd
        tag: docker.{{.Name}}    # TAG Es decir el hostname de cada contenedor
    deploy: #Para hacer el aprovisionamiento usando docker swarm y stack deploy
      restart_policy: #Configura cómo reiniciar los contenedores cuando se cierran
           condition: on-failure
           delay: 20s
           max_attempts: 3
           window: 120s
      mode: replicated
      replicas: 4 #indica las replicas que se quieren de ese contenedor
      resources:
        limits:
          cpus: "0.1" #restricción de cpu de 10%
          memory: 20M # Restricción de memoria de 20M
      placement:
        constraints:
          - node.role == worker # Para indicarle que es un nodo worker
      update_config:
        delay: 2s

  vizualizer:
      image: dockersamples/visualizer
      volumes:
         - /var/run/docker.sock:/var/run/docker.sock
      ports:
        - "8080:8080"
      networks:
        - webnet
      logging:
        driver: "fluentd" # Logging Driver 
        options:
         tag: visualizer   #TAG
      deploy:
          restart_policy:
             condition: on-failure
             delay: 20s
             max_attempts: 3
             window: 120s
          mode: replicated 
          replicas: 1
          update_config:
            delay: 2s
          placement:
             constraints: [node.role == manager]

  fluentd:
    image: fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
    ports:
      - "24224:24224/tcp" # puertos que usa fluentd
      - "24224:24224/udp"
    networks:
      - webnet
    deploy:
      restart_policy:
           condition: on-failure
           delay: 20s
           max_attempts: 3
           window: 120s
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      update_config:
        delay: 2s

  elasticsearch:
    image: elasticsearch
    ports:
      - "9200:9200"
    networks:
      - webnet
    environment: #variables de ambiente
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    logging:
        driver: "json-file" # Logging Driver 
        options:
          max-size: 10M
          max-file: 1  
    deploy:
      restart_policy:
        condition: on-failure
        delay: 20s
        max_attempts: 3
        window: 120s
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      update_config:
        delay: 2s
      resources:
        limits:
          memory: 1000M
    volumes:
      - my-vol:/usr/share/elasticsearch/data 

  kibana:
    image: kibana
    ports:
      - "5601:5601" 
    networks:
      - webnet
    logging:
        driver: "json-file"
        options:
           max-size: "10M"
           max-file: "1"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 20s
        max_attempts: 3
        window: 120s
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      update_config:
        delay: 2s

volumes:
  my-vol: #volumen interno para elasticsearch

networks:
webnet: #crea la red